server:
  port: 8080

spring:
  redis:
    host: 119.91.237.21
    port: 6379
  cache:
    redis:
      time-to-live: 1800000 #设置缓存过期时间
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://119.91.237.21:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射  119.91.237.21
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: D:\img\

tencent:
  sms:
    secretId: AKIDa0B7nEQM3UgfPu99tOddNs77rMbbMr66
    secretKey: mKdgU2LOBj14sQilY5NPBiz1nKbdPva0
    sdkAppId: 1400684835
    templateId: 1416184
    signName: 安逸i个人网站


